title: "Goofygiraffe06's Blog"
description: "Hack The Planet"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "goofygiraffe06.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Gofygiraffe06
github_username:  Goofygiraffe06

# Build settings
theme: jekyll-theme-console
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

header_pages:
  - index.markdown
  - whoami.markdown
footer: 'lots of lub <3, follow me on <a href="https://twitter.com/Goofygiraffe06">twitter</a>'
